xcodeproj 'DemoApp'
workspace '../SocketIO'

def import_pods
  pod 'OCMock',  '~> 2.1.1'
  pod 'Expecta', '~> 0.2.1'
  pod 'Specta',  '~> 0.2.1'
  pod 'SocketIO', :path => '../'
end

target :ios do
  platform :ios, '7.0'
  link_with 'DemoApp', 'DemoAppTests'
  import_pods
end
